name: Build (lazerl0rd fork)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out main repo
      uses: actions/checkout@main
      with:
        repository: 'lazerl0rd/dlssg-to-fsr3'

    - name: Checkout FSR SDK
      uses: actions/checkout@main
      with:
        repository: lazerl0rd/FidelityFX-SDK
        path: dependencies/FidelityFX-SDK
          
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@main
      with:
        version: latest
        cache: true

    - name: Build FSR
      shell: bash
      run: |
        cd dependencies/FidelityFX-SDK/sdk/
        ./BuildFidelityFXSDK.bat

    - name: Build
      shell: pwsh
      run: |
        ./Make-Release.ps1

    - name: Upload
      uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4
      with:
        name: Default
        path: './bin/built-packages/dlssg-to-fsr3-*.zip'
        if-no-files-found: ignore
