name: Build (Nukem9 (original) repo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out main repo
      uses: actions/checkout@main
      with:
        repository: 'Nukem9/dlssg-to-fsr3'
        submodules: 'recursive'

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@main
      with:
        version: latest
        cache: true

    - name: Install cmake
      uses: lukka/get-cmake@main
      with:
        cmakeVersion: latest
        ninjaVersion: latest

    - name: Build FSR
      shell: bash
      run: |
        cd dependencies/FidelityFX-SDK/sdk/
        ./BuildFidelityFXSDK.bat

    - name: Build
      shell: pwsh
      run: |
        ./Make-Release.ps1

    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: Default
        path: './bin/built-packages/dlssg-to-fsr3-*.zip'
        if-no-files-found: ignore